version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - run: npm install
      - run: npm test -- -u
workflows:
  build_test:
    jobs:
      - test
